Document: hmcfgusb
Title: Debian hmcfgusb Manual
Author: <insert document author here>
Abstract: This manual describes what hmcfgusb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hmcfgusb/hmcfgusb.sgml.gz

Format: postscript
Files: /usr/share/doc/hmcfgusb/hmcfgusb.ps.gz

Format: text
Files: /usr/share/doc/hmcfgusb/hmcfgusb.text.gz

Format: HTML
Index: /usr/share/doc/hmcfgusb/html/index.html
Files: /usr/share/doc/hmcfgusb/html/*.html
